In [52]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder
from sklearn.compose import ColumnTransformer

In [53]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [54]:
data=data.drop(columns=['RowNumber','CustomerId','Surname'],axis=1)

In [55]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [56]:
label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [57]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [58]:
preprocessor=ColumnTransformer(
    transformers=[
        ('onehot',OneHotEncoder(drop='first'),['Geography']),
        ('scaler',StandardScaler(),['CreditScore','Age','Tenure','Balance','NumOfProducts'])
    ],
    remainder='passthrough'
)

In [59]:
X=data.drop(columns=['EstimatedSalary'])
y=data['EstimatedSalary']

In [60]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [61]:
X_train_scaled=preprocessor.fit_transform(X_train)

In [62]:
X_test_scaled=preprocessor.transform(X_test)

In [63]:
import pickle

In [64]:
with open('labelencoderregression.pkl','wb') as file:
    pickle.dump(label_encoder,file)


with open('preprocessor_regression.pkl','wb') as file:
    pickle.dump(preprocessor,file)

ANN REGRESSION IMPLEMENTATION

In [65]:
import tensorflow as tf

In [66]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [67]:
#build the model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) #linear activation function applied  by default 
])

In [68]:
##Compile the model 
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [69]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                768

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2881 (11.25 KB)
Trainable params: 2881 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [70]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

import datetime

#set up Tensorboard 
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensornoard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [71]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [72]:
history = model.fit(
    X_train_scaled,y_train,
    validation_data=(X_test_scaled,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensornoard_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 100342.6484 - mae: 100342.6484 - val_loss: 98343.8672 - val_mae: 98343.8672
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 98852.9688 - mae: 98852.9688 - val_loss: 95280.7344 - val_mae: 95280.7344
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 93633.5703 - mae: 93633.5703 - val_loss: 87768.8047 - val_mae: 87768.8047
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 84247.0781 - mae: 84247.0781 - val_loss: 76873.3438 - val_mae: 76873.3438
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 72785.9375 - mae: 72785.9375 - val_loss: 65624.1406 - val_mae: 65624.1406
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 62775.0781 - mae: 62775.0781 - val_loss: 57600.8672 - val_mae: 57600.8672
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 56936.8672 - mae: 56936.8672 - val_loss: 54026.9766 - val_mae: 54026.9766
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 54696.8828 - mae: 54696.8828 - val_loss: 52985.5703 - val_mae: 52985.5703
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 54062.9922 - mae: 54062.9922 - val_loss: 52743.9805 - val_mae: 52743.9805
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 53857.1914 - mae: 53857.1914 - val_loss: 52644.2109 - val_mae: 52644.2109
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 53724.5078 - mae: 53724.5078 - val_loss: 52564.9492 - val_mae: 52564.9492
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 53617.7109 - mae: 53617.7109 - val_loss: 52476.6523 - val_mae: 52476.6523
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 53516.3555 - mae: 53516.3555 - val_loss: 52395.3477 - val_mae: 52395.3477
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 53419.3867 - mae: 53419.3867 - val_loss: 52315.4805 - val_mae: 52315.4805
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 53322.4609 - mae: 53322.4609 - val_loss: 52241.0625 - val_mae: 52241.0625
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 53232.6953 - mae: 53232.6953 - val_loss: 52158.8672 - val_mae: 52158.8672
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 53141.3984 - mae: 53141.3984 - val_loss: 52070.4883 - val_mae: 52070.4883
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 53052.6602 - mae: 53052.6602 - val_loss: 52015.8633 - val_mae: 52015.8633
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 52963.5391 - mae: 52963.5391 - val_loss: 51930.7617 - val_mae: 51930.7617
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 52877.1836 - mae: 52877.1836 - val_loss: 51845.6641 - val_mae: 51845.6641
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 52796.6992 - mae: 52796.6992 - val_loss: 51786.7227 - val_mae: 51786.7227
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 52709.4141 - mae: 52709.4141 - val_loss: 51718.1758 - val_mae: 51718.1758
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 52631.2344 - mae: 52631.2344 - val_loss: 51655.0195 - val_mae: 51655.0195
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 52550.3906 - mae: 52550.3906 - val_loss: 51581.7266 - val_mae: 51581.7266
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 52471.2031 - mae: 52471.2031 - val_loss: 51517.9102 - val_mae: 51517.9102
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 52396.0547 - mae: 52396.0547 - val_loss: 51470.4219 - val_mae: 51470.4219
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 52319.7969 - mae: 52319.7969 - val_loss: 51407.9297 - val_mae: 51407.9297
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 52244.1094 - mae: 52244.1094 - val_loss: 51364.8867 - val_mae: 51364.8867
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 52174.6836 - mae: 52174.6836 - val_loss: 51286.4141 - val_mae: 51286.4141
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 52102.7148 - mae: 52102.7148 - val_loss: 51242.1328 - val_mae: 51242.1328
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 52032.8594 - mae: 52032.8594 - val_loss: 51184.0352 - val_mae: 51184.0352
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 51963.0508 - mae: 51963.0508 - val_loss: 51134.9219 - val_mae: 51134.9219
Epoch 33/100
250/250 [==============================] - 1s 2ms/step - loss: 51894.2891 - mae: 51894.2891 - val_loss: 51084.4688 - val_mae: 51084.4688
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 51825.8750 - mae: 51825.8750 - val_loss: 51032.8672 - val_mae: 51032.8672
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 51756.8594 - mae: 51756.8594 - val_loss: 50983.6523 - val_mae: 50983.6523
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 51690.5234 - mae: 51690.5234 - val_loss: 50936.3984 - val_mae: 50936.3984
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 51629.9766 - mae: 51629.9766 - val_loss: 50895.5898 - val_mae: 50895.5898
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 51561.4219 - mae: 51561.4219 - val_loss: 50847.1133 - val_mae: 50847.1133
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 51498.9062 - mae: 51498.9062 - val_loss: 50804.3203 - val_mae: 50804.3203
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 51435.6406 - mae: 51435.6406 - val_loss: 50749.6992 - val_mae: 50749.6992
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 51381.2891 - mae: 51381.2891 - val_loss: 50708.4141 - val_mae: 50708.4141
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 51318.2891 - mae: 51318.2891 - val_loss: 50677.4492 - val_mae: 50677.4492
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 51262.6758 - mae: 51262.6758 - val_loss: 50633.7383 - val_mae: 50633.7383
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 51205.9102 - mae: 51205.9102 - val_loss: 50596.9805 - val_mae: 50596.9805
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 51151.2656 - mae: 51151.2656 - val_loss: 50552.2070 - val_mae: 50552.2070
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 51098.8086 - mae: 51098.8086 - val_loss: 50534.7852 - val_mae: 50534.7852
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 51044.2383 - mae: 51044.2383 - val_loss: 50484.0039 - val_mae: 50484.0039
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 50988.4570 - mae: 50988.4570 - val_loss: 50450.2109 - val_mae: 50450.2109
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 50940.6797 - mae: 50940.6797 - val_loss: 50425.3789 - val_mae: 50425.3789
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 50886.2656 - mae: 50886.2656 - val_loss: 50398.2656 - val_mae: 50398.2656
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 50837.2695 - mae: 50837.2695 - val_loss: 50361.8906 - val_mae: 50361.8906
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 50785.9141 - mae: 50785.9141 - val_loss: 50326.7617 - val_mae: 50326.7617
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 50742.4609 - mae: 50742.4609 - val_loss: 50294.1953 - val_mae: 50294.1953
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 50694.9883 - mae: 50694.9883 - val_loss: 50268.8867 - val_mae: 50268.8867
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 50645.6719 - mae: 50645.6719 - val_loss: 50239.0664 - val_mae: 50239.0664
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 50598.3086 - mae: 50598.3086 - val_loss: 50213.4648 - val_mae: 50213.4648
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 50557.4922 - mae: 50557.4922 - val_loss: 50183.3438 - val_mae: 50183.3438
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 50510.6016 - mae: 50510.6016 - val_loss: 50162.0938 - val_mae: 50162.0938
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 50464.9492 - mae: 50464.9492 - val_loss: 50125.7070 - val_mae: 50125.7070
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 50422.6094 - mae: 50422.6094 - val_loss: 50107.4531 - val_mae: 50107.4531
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 50382.3789 - mae: 50382.3789 - val_loss: 50086.1445 - val_mae: 50086.1445
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 50339.4766 - mae: 50339.4766 - val_loss: 50062.9570 - val_mae: 50062.9570
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 50304.0703 - mae: 50304.0703 - val_loss: 50053.6094 - val_mae: 50053.6094
Epoch 64/100
250/250 [==============================] - 1s 2ms/step - loss: 50271.3047 - mae: 50271.3047 - val_loss: 50028.2617 - val_mae: 50028.2617
Epoch 65/100
250/250 [==============================] - 1s 2ms/step - loss: 50228.0312 - mae: 50228.0312 - val_loss: 50014.6211 - val_mae: 50014.6211
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 50192.9336 - mae: 50192.9336 - val_loss: 50006.9648 - val_mae: 50006.9648
Epoch 67/100
250/250 [==============================] - 1s 2ms/step - loss: 50156.8281 - mae: 50156.8281 - val_loss: 49991.7266 - val_mae: 49991.7266
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 50127.1484 - mae: 50127.1484 - val_loss: 49973.0586 - val_mae: 49973.0586
Epoch 69/100
250/250 [==============================] - 1s 2ms/step - loss: 50095.5430 - mae: 50095.5430 - val_loss: 49957.1133 - val_mae: 49957.1133
Epoch 70/100
250/250 [==============================] - 1s 2ms/step - loss: 50070.3359 - mae: 50070.3359 - val_loss: 49941.3828 - val_mae: 49941.3828
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 50034.5312 - mae: 50034.5312 - val_loss: 49936.5312 - val_mae: 49936.5312
Epoch 72/100
250/250 [==============================] - 1s 2ms/step - loss: 50014.9688 - mae: 50014.9688 - val_loss: 49925.6758 - val_mae: 49925.6758
Epoch 73/100
250/250 [==============================] - 1s 2ms/step - loss: 49982.6328 - mae: 49982.6328 - val_loss: 49907.4062 - val_mae: 49907.4062
Epoch 74/100
250/250 [==============================] - 1s 2ms/step - loss: 49958.0938 - mae: 49958.0938 - val_loss: 49923.4570 - val_mae: 49923.4570
Epoch 75/100
250/250 [==============================] - 1s 2ms/step - loss: 49934.8320 - mae: 49934.8320 - val_loss: 49904.8516 - val_mae: 49904.8516
Epoch 76/100
250/250 [==============================] - 1s 2ms/step - loss: 49915.5078 - mae: 49915.5078 - val_loss: 49906.4336 - val_mae: 49906.4336
Epoch 77/100
250/250 [==============================] - 1s 2ms/step - loss: 49892.4727 - mae: 49892.4727 - val_loss: 49894.9961 - val_mae: 49894.9961
Epoch 78/100
250/250 [==============================] - 1s 2ms/step - loss: 49872.9336 - mae: 49872.9336 - val_loss: 49880.0039 - val_mae: 49880.0039
Epoch 79/100
250/250 [==============================] - 1s 2ms/step - loss: 49853.4062 - mae: 49853.4062 - val_loss: 49860.2812 - val_mae: 49860.2812
Epoch 80/100
250/250 [==============================] - 1s 2ms/step - loss: 49837.1719 - mae: 49837.1719 - val_loss: 49858.2461 - val_mae: 49858.2461
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 49822.5234 - mae: 49822.5234 - val_loss: 49862.3867 - val_mae: 49862.3867
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 49802.2266 - mae: 49802.2266 - val_loss: 49876.1992 - val_mae: 49876.1992
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 49795.9609 - mae: 49795.9609 - val_loss: 49867.0234 - val_mae: 49867.0234
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 49774.9922 - mae: 49774.9922 - val_loss: 49868.3281 - val_mae: 49868.3281
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 49762.8945 - mae: 49762.8945 - val_loss: 49878.3633 - val_mae: 49878.3633

In [73]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [75]:
%tensorboard --logdir regressionlogs/fit

In [76]:
print(log_dir)

regressionlogs/fit/20260618-210121

In [77]:
import os

for root, dirs, files in os.walk(log_dir):
    print(root)
    print(files)

regressionlogs/fit/20260618-210121
[]
regressionlogs/fit/20260618-210121\train
['events.out.tfevents.1781796681.OJASPC.57996.3.v2']
regressionlogs/fit/20260618-210121\validation
['events.out.tfevents.1781796682.OJASPC.57996.4.v2']

In [79]:
# evaluate the model on the test data
test_loss,test_mae=model.evaluate(X_test_scaled,y_test)
print(f'TEST MAE : {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 49858.2461 - mae: 49858.2461
TEST MAE : 49858.24609375

In [80]:
model.save('regressionmodel.h5')

c:\Users\ojass\OneDrive\Desktop\Udemy\DeepLearning\ANN\venvDL\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(